//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementBase.LibraryEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookRequestDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BookRequestDetail()
        {
            this.CheckInCheckOutDetails = new HashSet<CheckInCheckOutDetail>();
        }
    
        public int RequestId { get; set; }
        public int BookId { get; set; }
        public int UserId { get; set; }
        public int StatusId { get; set; }
        public System.DateTime RequestDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string Comments { get; set; }
        public bool IsActive { get; set; }
    
        public virtual BookDetail BookDetail { get; set; }
        public virtual Status Status { get; set; }
        public virtual UserDetail UserDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CheckInCheckOutDetail> CheckInCheckOutDetails { get; set; }
    }
}
