//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementBase.LibraryEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BookDetail()
        {
            this.BookRequestDetails = new HashSet<BookRequestDetail>();
        }
    
        public int BookId { get; set; }
        public string BookName { get; set; }
        public string ISBNNumber { get; set; }
        public decimal Price { get; set; }
        public int CategoryId { get; set; }
        public string AuthorName { get; set; }
        public string BookReviewLink { get; set; }
        public int TotalNoOfCopies { get; set; }
        public bool IsAvailable { get; set; }
        public string Comments { get; set; }
        public System.DateTime PurchasedDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public string Publisher { get; set; }
    
        public virtual CategoryDetail CategoryDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookRequestDetail> BookRequestDetails { get; set; }
    }
}
