//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementBase.LibraryEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewProposalDetail
    {
        public int ProposalId { get; set; }
        public string BookName { get; set; }
        public string Category { get; set; }
        public string Author { get; set; }
        public int ProposedBy { get; set; }
        public int ProposedStatusId { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string Comments { get; set; }
        public bool IsActive { get; set; }
        public string Publisher { get; set; }
        public System.DateTime ProposedDate { get; set; }
    
        public virtual Status Status { get; set; }
        public virtual UserDetail UserDetail { get; set; }
    }
}
