//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementBase.LibraryEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_GetBookDetails
    {
        public int BookId { get; set; }
        public string BookName { get; set; }
        public string CategoryName { get; set; }
        public string AuthorName { get; set; }
        public string Publisher { get; set; }
        public string ISBNNumber { get; set; }
        public string BookReviewLink { get; set; }
        public int TotalNoOfCopies { get; set; }
        public Nullable<int> RequestedCopy { get; set; }
        public Nullable<int> IssuedCopy { get; set; }
        public Nullable<int> AvailableCopy { get; set; }
    }
}
